services:
    api-partner-gateway:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
    #     depends_on:
    #         - redis

    # redis:
    #     image: redis:7-alpine
    #     ports:
    #         - '6379:6379'
