version: '3.8'

services:
  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    depends_on:
      - redis
    ports:
      - "3000:3000"
